// <auto-generated />
using ASME_Forms.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASME_Forms.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230624003812_AddASME_CBITable")]
    partial class AddASME_CBITable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.5.23280.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASME_Forms.Models.ASME_CBI", b =>
                {
                    b.Property<int>("JOB_TRAVELER_NUMBER")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JOB_TRAVELER_NUMBER"));

                    b.Property<int>("BASIC_TANK_NUMBER")
                        .HasColumnType("int");

                    b.Property<string>("DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DWG_NUMBER")
                        .HasColumnType("int");

                    b.Property<int>("HX_NUMBER")
                        .HasColumnType("int");

                    b.Property<int>("MVP_NUMBER")
                        .HasColumnType("int");

                    b.Property<int>("NATL_BD_NUMBER")
                        .HasColumnType("int");

                    b.Property<int>("PART_NUMBER")
                        .HasColumnType("int");

                    b.HasKey("JOB_TRAVELER_NUMBER");

                    b.ToTable("ASME_CBI");
                });
#pragma warning restore 612, 618
        }
    }
}
